---
kind: pipeline
type: exec
name: default

clone:
  disable: true

steps:
- name: deploy
  commands:
  - id
  - git clone git@github.com:ntr1x/com.southhillslab.starter.git
  - cd ./com.southhillslab.starter
  - yarn rebuild:web
  - yarn restart:web
  when:
    branch: master
